<h2>Co je uvnitř</h3>

<h3>Displej</h3>
<p>Z&nbsp;pohledu hardwarové výbavy iPhone 5c kopíruje předchozí generaci iPhone 5. Novinka disponuje čtyřpalcovým displejem s&nbsp;rozlišením 1 136 × 640 pixelů. To je mezi současnými smartphony průměr na úrovni střední třídy. Čtyři palce mohou někomu přijít málo, na druhou stranu zůstala spolehlivě zachovaná možnost komfortně držet a&nbsp;ovládat telefon jednou rukou. Přesto si myslíme, že displej iPhonu měl v&nbsp;poslední generaci narůst alespoň na 4,3 palce. Displej má tradičně velmi dobrou čitelnost na slunci, trpí minimálními odlesky a&nbsp;vyznačuje se výbornými pozorovacími úhly i&nbsp;citlivostí na dotek.</p>

<h3>Hardware</h3>
<p>Nový iPhone 5c je poháněn starší generací čipsetu Apple A6 s&nbsp;dvoujádrovým procesorem taktovaným na 1,3 GHz. Ve výkonnostních testech se může srovnávat například s&nbsp;čipsetySnapdragon S4 Pro se čtyřjádrovými procesorem (používá např. LG Optimus G, Sony Xperia Z&nbsp;nebo Xiaomi Mi2), ale zaostává za zařízeními se Snapdragonem 800. Oproti top modelu iPhone 5s dosahuje iPhone 5c v&nbsp;některých benchmarcích jen poloviční skóre.</p>
<p>Hbitost a&nbsp;odladěnost systému je ale výborná. Apple iPhone 5c přichází s&nbsp;novým systémem iOS 7, který je kompletně redesignován a&nbsp;obohacen o&nbsp;nové funkce, například o&nbsp;lištu s&nbsp;ovládacím panelem či nové notifikační centrum. Podrobně jsme se systému věnovali v&nbsp;samostatném velkém testu.</p>

<h3>Baterie</h3>
<p>Samozřejmostí je podpora rychlých LTE sítí. U&nbsp;nás ale stále ve větší míře využijeme připojení HSDPA a&nbsp;HSUPA, které podporuje i&nbsp;technologii DualCarrier a&nbsp;tedy teoretické rychlosti 42 Mbit/s pro stahování a&nbsp;5,76 Mbit/s pro upload dat. Nechybí Wi-Fi či energeticky méně náročný Bluetooth 4.0. Citlivost modulů je příkladná, problémy se stabilitou bezdrátového připojení vás rozhodně trápit nebudou, iPhone 5c je na tom v&nbsp;tomto ohledu velmi dobře. Také fixace satelitů GPS probíhá takřka okamžitě a&nbsp;signál se drží i&nbsp;v&nbsp;centru měst.</p>
<p>Naopak o&nbsp;NFC pro bezkontaktní platby či rychlé párování s&nbsp;bezdrátovým příslušenstvím si stále budete muset nechat zdát. Stejně tak chybí tradičně i&nbsp;slot pro paměťové karty, což může být při pohledu na ceny jednotlivých paměťových verzí a&nbsp;absenci modelu s&nbsp;64GB pamětí trochu problém. Vysoká cena za paměť ale patří ke koloritu iPhonů a&nbsp;jablečných produktů obecně. Baterie iPhonu 5c narostla oproti předchozí generaci o&nbsp;symbolických 70 mAh na kapacitu 1510 mAh. Při reálném používání to samozřejmě nepoznáte. Výdrž stále balancuje na hranici jednoho až dvou dnů v&nbsp;závislosti na zatížení.</p>
