<h2>Vzhled</h2>

<h3>Design</h3>
<p>Inženýři v&nbsp;Cupertinu to vymysleli opravdu famózně. Doposud to fungovalo s&nbsp;iPhony tak, že každý rok s&nbsp;představením eskového modelu (3GS, 4S, 5S) jeho předchozí verze (3G, 4, 5) zlevnila. Apple to vždy během prezentace zmínil, ale o&nbsp;sto dolarů cenově atraktivnějšímu loňskému modelu jinak nevěnoval výraznější pozornost.</p>
<p>To se letos změnilo. Loňský hliníkový iPhone 5 oblékl do plastů, nazval ho iPhone 5c a&nbsp;dal mu obvyklou nižší cenovku, kterou by si po vzoru předešlých modelů tak či onak rok starý iPhone 5 vysloužil. Je to tak, iPhone 5c není nic jiného než loňský iPhone 5, jehož hliníkové tělo po roce nahradil levnější, ale zato barevnější polykarbonát. Předchozí iPhone 5 zmizel z&nbsp;pultů oficiálních obchodů. Je nutno smutnit za kovovým telefonem, nebo se i&nbsp;na plastovém zpracování najdou nějaké výhody?</p>
<p>Díky velké reklamní kampani barevný model iPhone 5c kupují uživatelé určitě mnohem více, než by kupovali iPhone 5 po uvedení iPhonu 5s. Tomu se prostě říká dokonalé využití skladových zásob a&nbsp;maximalizování marží, takže manažeři z&nbsp;Kalifornie zaslouží potlesk. Vůbec jim přitom nemusí vadit, že se iPhone 5c v&nbsp;absolutních číslech neprodává zase tak dobře, což nakonec ani nikdo nečekal. Vývoj a&nbsp;výroba plastového šasi byly bohatě zaplaceny a&nbsp;hlavně se podařilo zužitkovat rok staré komponenty.</p>
<p>Nový outfit pasuje k&nbsp;novému prostředí</p>
<p>O&nbsp;čem tedy vlastně psát, když jde jen o&nbsp;překrytovaný loňský model? Můžeme vás odkázat na recenzi iPhonu 5 a&nbsp;kvůli novému prostředí takéna recenzi systému iOS7. Zbytek prosvištíme letem světem s&nbsp;tím, že největší pasáž této recenze bude patřit právě designu a&nbsp;konstrukci.</p>
<p>Apple iPhone 5c přichází v&nbsp;pěti barevných provedeních. Svěží pastelové barvy zadního krytu novinky (bílá, modrá, žlutá, zelená a&nbsp;růžová) velmi dobře ladí s&nbsp;designovým pojetím výrazně přepracovaného systému iOS 7. Na test jsme dostali limetkově zelený iPhone 5c, který podle našeho mínění patří spolu s&nbsp;modrým k&nbsp;nejatraktivnějším barvám.</p>

<h3>Konstrukce</h3>
<p>Kvalita zpracování je na nejvyšší úrovni a&nbsp;jakékoliv vrzání je díky jednolité konstrukci bez odnímatelných prvků vyloučeno. Apple nezklamal a&nbsp;potvrdil, že kvalitní plastové telefony od dob iPhonu 3GS vyrábět nezapomněl. Polykarbonátový zadní kryt má lesklou povrchovou úpravu, otisky na něm nijak výrazně neulpívají, nebo minimálně na zeleném těle nejsou tolik vidět.</p>
<p>Připomeňme, že polykarbonát, který poprvé ve větším měřítku začala v&nbsp;konstrukci smartphonů používat Nokia, má v&nbsp;celé struktuře stejnou barvu. Není to jen na povrchu nabarvený plast. Pokud tedy dojde k&nbsp;nějakému pádu a&nbsp;následnému poškrábání, nebude tato rána na iPhonu 5c až tak viditelná. Trvanlivost materiálu zejména ve srovnání s&nbsp;hliníkovými slitinami je ale sporná a&nbsp;reflektovat ji budou až dlouhodobější uživatelské zkušenosti.</p>
<p>Hrany iPhonu 5c jsou příjemně oblé, což je jedna z&nbsp;nejvýraznějších výhod modelu 5c proti loňské pětkové generaci, ale i&nbsp;letošnímu vlajkovému modelu 5s. Díky tomu telefon dobře padne do dlaně a&nbsp;nelze si stěžovat na zařezávání ostrých hran do ruky. Oproti staršímu iPhonu 5 či dražšímu iPhonu 5s ale testovaný model lehce nabral na hmotnosti i&nbsp;tloušťce. Namísto v&nbsp;hliníku zabalených 112 gramů o&nbsp;tloušťce 7,6 mm dorostl iPhone 5c do tloušťky 9 mm a&nbsp;hmotnosti 132 gramů. Rozdíly však poznáte jen při přímém porovnání obou iPhonů vedle sebe.</p>
